---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-core-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-azure-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-workload-clusters
