---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedControlPlane
metadata:
  name: ${cluster_name}
  namespace: capi-workload-clusters
spec:
  version: v1.26.6
  resourceGroupName: ${resource_group}
  subscriptionID: ${subscription_id}
  location: ${cluster_location}
  sshPublicKey: ${public_key}
  networkPlugin: kubenet
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: ${cluster_name}
    namespace: capi-workload-clusters
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedCluster
metadata:
  name: ${cluster_name}
  namespace: capi-workload-clusters
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: system
  namespace: capi-workload-clusters
spec:
  mode: System
  sku: standard_d8s_v5
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  name: ${cluster_name}
  namespace: capi-workload-clusters
spec:
  type: WorkloadIdentity
  clientID: ${client_id}
  tenantID: ${tenant_id}
  allowedNamespaces:
    list:
      - capi-azure-system
      - capi-workload-clusters
